blank_issues_enabled: false  
contact_links:
  - name: ğŸ› Bug Report
    url: https://github.com/lucaarcteam/ArcheOS-software-list/issues/new?assignees=&labels=bug&template=bug_report.md
    about: Report a problem or bug in the repository.
  - name: ğŸ’¡ Feature Request
    url: https://github.com/lucaarcteam/ArcheOS-software-list/issues/new?assignees=&labels=enhancement&template=feature_request.md
    about: Suggest a new feature or improvement.
  - name: â“ Question
    url: https://github.com/lucaarcteam/ArcheOS-software-list/issues/new?assignees=&labels=question&template=question.md
    about: Ask a question about the project.
